### ISSUE TITLE
Extending default query with Yoast Seo

### ISSUE THREAD

**Issue by enricodeleo** [vernaillen/wpnuxt-module#17] opened 2024-02-20 14:24 UTC
Hello there and thank you for this great module. It's a great building block for a modern Wordpress stack!

I'm having hard times figuring out how to extend the `wp.gql` in order to always include

```
seo {
    metaDesc
    title
    fullHead
}
```

for pages and posts. I think it would be super useful in order to have full control of the SEO metas.  Of course I already extended the graphql thanks to a plugin.

Any ideas?

**Comment by vernaillen** [comment] 2024-03-01 19:25
Hi Enrico

Thanks for trying out the module, glad you like it.    It's still in an early stage and I thought I was the only one using it so far :D

What you describe would indeed be very useful, but is not possible at the moment.  
I did already provide a way to extend the schema with extra Fragments and Queries, which can be used for adding Custom Post Types.
But it doesn't allow to modify an already existing fragment, like a Page or Post. 

The issue is that the wp.gql provided by the module is always loaded, so if you try to override the Page or Post fragment, it will throw errors like this
`Error: Not all fragments have an unique name: Page, Post`

What I can do, is provide a config setting to disable the original wp.gql.    And you can then copy the complete wp.gql into your nuxt app and extend the Fragments with the extra seo fields.

**Comment by enricodeleo** [comment] 2024-03-03 11:10
Well I'm quite a connoisseur when it comes to uncovering gems @vernaillen 😊

Yes checking the source code I stumbled upon the possibility to extend the graphql queries with a custom file but I end up with the exact same error you mentioned. 
I think that the possibility of overriding it could be a good improvement for a first iteration over the problem. I don't see at the moment how to approach this in a more flexible way but I hope I can contribute if I come up with a better suggestion.

Speaking of config settings, I've encountered some challenges in attempting to disable the multiCache function. The only workaround I've managed to come up with was to independently install the multicache module, otherwise I couldn't set cache to false. Even after that the contents from graphql are still cached and that's quite a problem during development.

This module is super promising, thank you for this!

**Comment by vernaillen** [comment] 2024-03-03 16:55
v0.2.6 has just been released including your fix for the srcDir.    
There's a separate ticket for the multiCache issue, which I will look into later.

I also added an example how to override the existing Page and Post fragments in examples/yoastseo.

Thanks for the feedback on the module and the contribution :)

**Comment by vernaillen** [comment] 2024-03-03 16:56
Closing this ticket now. of course new ones are always welcome

**Closed by vernaillen** 2024-03-03 16:56 UTC

**Comment by enricodeleo** [comment] 2024-03-03 19:07
I did see the example and already tested it. It works now even with srcDir. Thank a lot!
